#!/usr/bin/perl
$max=32;$mm=$max-1;

open A,">leonardo.cc";
print A <<EOF;
// This file is generated by the leonardo.pl script and is not intended to be
// edited by hand.

EOF
$b=1;$c=-1;
print A "const int ls_smoothsort::smb[$max]={";
foreach (0..$mm) {
	print A "$b".($_==$mm?"};\n":",");
	$d=$b+$c+1;$c=$b;$b=$d;
}

$b=1;$c=-1;
print A "const int ls_smoothsort::smc[$max]={";
foreach (0..$mm) {
	print A "$c".($_==$mm?"};\n":",");
	$d=$b+$c+1;$c=$b;$b=$d;
}

$b=1;$c=-1;
print A "const int ls_smoothsort::smd[$max]={";
foreach (0..$mm) {
	$d=$b-$c;
	print A "$d".($_==$mm?"};\n":",");
	$d=$b+$c+1;$c=$b;$b=$d;
}
close A;

open A,">leonardo.hh";
print A <<EOF;
// This file is generated by the leonardo.pl script and is not intended to be
// edited by hand.

static const int smb[$max];
static const int smc[$max];
static const int smd[$max];
EOF
close A;
